apiVersion: v1
kind: Service
metadata:
  name: pg-16-4-lb
  labels:
    app: postgres-16-4
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      name: "postgres"
  selector:
    app: postgres-16-4
