apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addon-localstack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - chart: localstack
      repoURL: "https://localstack.github.io/helm-charts"
      targetRevision: 0.6.17
      helm:
        valuesObject:
          startServices: "iam,sns,sts"
          service:
            type: LoadBalancer
            externalServicePorts: ~
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: localstack
    server: https://kubernetes.default.svc
  project: default
