apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-promtail
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      chart: "promtail"
      targetRevision: "6.16.4"
      helm:
#         https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml
        valueFiles:
          - "$values/cluster/grafana/grafana-promtail-config.yaml"
    - repoURL: https://github.com/meschbach/local-k8s.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: grafana-promtail
    server: https://kubernetes.default.svc
  project: default
