deploymentMode: SingleBinary
loki:
  commonConfig:
    replication_factor: 1
  storage:
    type: 'filesystem'
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        index:
          prefix: loki_index_
          period: 24h
        object_store: filesystem # we're storing on filesystem so there's no real persistence here.
        schema: v13
singleBinary:
  replicas: 1
  persistence:
    storageClass: local-path
read:
  replicas: 0
backend:
  replicas: 0
write:
  replicas: 0
lokiCanary:
  enabled: false
resultsCache:
  enabled: false
gateway:
  enabled: false
monitoring:
  selfMonitoring:
    enabled: false
test:
  enabled: false