config:
  clients:
    - url: http://loki-headless.grafana-loki.svc.workshop.k8s:3100/loki/api/v1/push
      tenant_id: 1
  snippets:
    extraScrapeConfigs: |
      - job_name: journal
        journal:
          json: false
          max_age: 12h
          path: /var/log/journal
          labels:
            job: systemd-journal
#        relabel_configs:
#          - source_labels: ['__journal__systemd_unit']
#            target_label: 'unit'
#          - source_labels: ['__journal__hostname']
#            target_label: 'hostname'
#          - source_labels: ['__journal_priority_keyword']
#            target_label: level

extraVolumes:
  - name: journal
    hostPath:
      path: /var/log/journal
  - name: machine-id
    hostPath:
      path: /etc/machine-id

extraVolumeMounts:
  - name: journal
    mountPath: /var/log/journal
    readOnly: true
  - name: machine-id
    mountPath: /etc/machine-id
    readOnly: true